from django.urls import path
from . import views
from . import views_actions as act
from . import views_browse as browse
from . import views_group_ops as gops
from . import views_meta as meta
from . import views_albums as albums
from . import views_friends as friends
from . import views_events as events
from . import views_inbox as inbox
from . import views_wall_ops as wall
from . import views_pages as pages
from . import views_apps as apps
from . import views_gifts as gifts
from . import views_birthdays as birthdays
from . import views_classic as classic
from . import views_era2010 as era
from . import views_era2011 as era11
from . import views_era2012 as era12
from . import views_era2013 as era13
from . import views_era2014 as era14
from . import views_osm as osm_views
from . import views_platform as platform
from . import views_developers as developers
from . import views_app_api as app_api
from . import realtime as rt
from .poker import api as poker_api

urlpatterns = [
    path("geo/suggest", osm_views.geo_suggest, name="geo.suggest"),
    path("geo/ping", osm_views.geo_ping, name="geo.ping"),
    path("up", meta.up, name="up"),
    path("", views.home, name="home"),
    path("feed", views.feed, name="feed"),
    path("people", friends.people, name="people"),
    path("friends", friends.friends_home, name="friends"),
    path("friends/lists", classic.lists_home, name="friends.lists"),
    path("friends/lists/<int:pk>/delete", classic.list_delete, name="friends.lists.delete"),
    path("friends/lists/<int:pk>", classic.list_show, name="friends.lists.show"),
    path("invite", friends.invite_mine, name="invite.mine"),
    path("i/<str:code>", friends.invite_show, name="invite.show"),
    path("pages", pages.pages_home, name="pages"),
    path("pages/<int:pk>/edit", pages.page_edit, name="pages.edit"),
    path("pages/<int:pk>/delete", pages.page_delete, name="pages.delete"),
    path("pages/<int:pk>/fan", pages.page_fan, name="pages.fan"),
    path("pages/<int:pk>/unfan", pages.page_unfan, name="pages.unfan"),
    path("pages/<int:pk>/posts", pages.page_post, name="pages.posts"),
    path("pages/<int:pk>/events", pages.page_event_create, name="pages.events"),
    path("pages/<int:pk>/milestones", era12.page_milestone_create, name="pages.milestones"),
    path("pages/<int:pk>/milestones/<int:mid>/delete", era12.page_milestone_delete, name="pages.milestones.delete"),
    path("pages/<int:pk>/cover", era12.page_cover_upload, name="pages.cover"),
    path("pages/<int:pk>/cover/clear", era12.page_cover_clear, name="pages.cover.clear"),
    path("pages/<int:pk>", pages.page_show, name="pages.show"),
    path("pages/<slug:slug>", pages.page_slug_redirect, name="pages.slug"),
    path("apps", apps.apps_home, name="apps"),
    path("developers", developers.developer_home, name="developers"),
    path("developers/docs", developers.developer_docs, name="developers.docs"),
    path("developers/new", developers.developer_new, name="developers.new"),
    path("developers/<slug:slug>/edit", developers.developer_edit, name="developers.edit"),
    path("developers/<slug:slug>/rotate", developers.developer_rotate, name="developers.rotate"),
    path("developers/<slug:slug>/delete", developers.developer_delete, name="developers.delete"),
    path("api/oauth/access_token", app_api.oauth_access_token, name="api.oauth.token"),
    path("api/app/me", app_api.api_me, name="api.app.me"),
    path("api/app/friends", app_api.api_friends, name="api.app.friends"),
    path("api/app/verify_signed", app_api.api_verify_signed, name="api.app.verify"),
    path("apps/<slug:slug>/install", platform.app_install, name="apps.install"),
    path("apps/<slug:slug>/uninstall", platform.app_uninstall, name="apps.uninstall"),
    path("apps/<slug:slug>/canvas", platform.app_canvas, name="apps.canvas"),
    path("apps/<slug:slug>/authorize", platform.app_authorize, name="apps.authorize"),
    path("apps/<slug:slug>/launch", platform.app_launch, name="apps.launch"),
    path("apps/poker/api/game/<int:game_id>", poker_api.table_state, name="poker.api.game"),
    path("apps/poker/api/game/<int:game_id>/act", poker_api.table_act, name="poker.api.act"),
    path("apps/poker/api/room/<int:room_id>", poker_api.room_state, name="poker.api.room"),
    path("apps/<slug:slug>", era12.app_show, name="apps.show"),
    path("applications", meta.redirect_permanent, {"to": "/apps"}, name="applications.legacy"),
    path("collections", era12.collections_home, name="collections"),
    path("collections/<int:pk>", era12.collection_show, name="collections.show"),
    path("collections/<int:pk>/edit", era12.collection_edit, name="collections.edit"),
    path("collections/<int:pk>/delete", era12.collection_delete, name="collections.delete"),
    path("collections/<int:pk>/cover", era12.collection_cover_upload, name="collections.cover"),
    path("collections/<int:pk>/cover/clear", era12.collection_cover_clear, name="collections.cover.clear"),
    path("collections/<int:pk>/items", era12.collection_item_add, name="collections.items"),
    path("collections/<int:pk>/items/<int:item_id>/delete", era12.collection_item_delete, name="collections.items.delete"),
    path("graph", era13.graph_search, name="graph"),
    path("hashtag/<str:name>", era13.hashtag_show, name="hashtag"),
    path("nearby", era13.nearby_friends, name="nearby"),
    path("trending", era13.trending_home, name="trending"),
    path("saves", era14.saves_home, name="saves"),
    path("saves/add", era14.save_add, name="saves.add"),
    path("saves/<int:pk>/delete", era14.save_delete, name="saves.delete"),
    path("posts/<int:post_id>/save", era14.save_post_toggle, name="posts.save"),
    path("safety", era14.safety_home, name="safety"),
    path("safety/<int:pk>", era14.safety_show, name="safety.show"),
    path("gifts", gifts.gifts_home, name="gifts"),
    path("gifts/send", gifts.gift_send, name="gifts.send"),
    path("gifts/send/<int:pk>", gifts.gift_send_quick, name="gifts.send.quick"),
    path("birthdays", birthdays.birthdays_home, name="birthdays"),
    path("anniversaries", birthdays.anniversaries_home, name="anniversaries"),
    path("networks", classic.networks_home, name="networks"),
    path("links", classic.links_home, name="links"),
    path("videos", classic.videos_home, name="videos"),
    path("places", era.places_home, name="places"),
    path("places/<int:pk>/edit", era.place_edit, name="places.edit"),
    path("places/<int:pk>/delete", era.place_delete, name="places.delete"),
    path("places/<int:pk>/checkins/<int:checkin_id>/delete", era.place_checkin_delete, name="places.checkins.delete"),
    path("places/<int:pk>/reviews/<int:review_id>/delete", era.place_review_delete, name="places.reviews.delete"),
    path("places/<int:pk>", era.place_show, name="places.show"),
    path("og", era11.og_home, name="og"),
    path("og/publish", era11.og_publish, name="og.publish"),
    path("profile/<int:pk>/follow", era11.follow_toggle, name="profile.follow"),
    path("profile/<int:pk>/milestones", era11.milestone_create, name="profile.milestones"),
    path("profile/<int:pk>/milestones/<int:mid>/delete", era11.milestone_delete, name="profile.milestones.delete"),
    path("profile/cover", era11.cover_upload, name="profile.cover"),
    path("profile/cover/clear", era11.cover_clear, name="profile.cover.clear"),
    path("questions", era.questions_home, name="questions"),
    path("questions/<int:pk>/edit", era.question_edit, name="questions.edit"),
    path("questions/<int:pk>/delete", era.question_delete, name="questions.delete"),
    path("questions/<int:pk>", era.question_show, name="questions.show"),
    path("questions/<int:pk>/answers/<int:answer_id>/vote", era.question_vote, name="questions.vote"),
    path("questions/<int:pk>/answers/<int:answer_id>/delete", era.question_answer_delete, name="questions.answers.delete"),
    path("polls", era.polls_home, name="polls"),
    path("polls/<int:pk>/edit", era.poll_edit, name="polls.edit"),
    path("polls/<int:pk>/delete", era.poll_delete, name="polls.delete"),
    path("polls/<int:pk>", era.poll_show, name="polls.show"),
    path("polls/<int:pk>/options/<int:option_id>/vote", era.poll_vote, name="polls.vote"),
    path("marketplace", classic.marketplace_home, name="marketplace"),
    path("marketplace/<int:pk>/edit", classic.marketplace_edit, name="marketplace.edit"),
    path("marketplace/<int:pk>/delete", classic.marketplace_delete, name="marketplace.delete"),
    path("marketplace/<int:pk>", classic.marketplace_show, name="marketplace.show"),
    path("blocked", classic.blocked_home, name="blocked"),
    path("mobile", classic.mobile_home, name="mobile"),
    path("notes", classic.notes_home, name="notes"),
    path("notes/store", act.note_create, name="notes.store"),
    path("groups", browse.groups, name="groups"),
    path("groups/<int:pk>/edit", gops.group_edit, name="groups.edit"),
    path("groups/<int:pk>/delete", gops.group_delete, name="groups.delete"),
    path("groups/<int:pk>/members", gops.group_members, name="groups.members"),
    path("groups/<int:pk>/join", gops.group_join, name="groups.join"),
    path("groups/<int:pk>/leave", gops.group_leave, name="groups.leave"),
    path("groups/<int:pk>/join/cancel", gops.join_cancel, name="groups.join.cancel"),
    path("groups/<int:pk>/invite", gops.group_invite, name="groups.invite"),
    path("groups/<int:pk>/events", gops.group_event_create, name="groups.events"),
    path("groups/<int:pk>/members/<int:user_id>/manage", gops.member_manage, name="groups.members.manage"),
    path("groups/<int:pk>/join/<int:request_id>/accept", gops.join_accept, name="groups.join.accept"),
    path("groups/<int:pk>/join/<int:request_id>/reject", gops.join_reject, name="groups.join.reject"),
    path("groups/<int:pk>/posts", gops.group_post, name="groups.posts"),
    path("groups/<int:pk>/posts/<int:post_id>/edit", gops.group_post_edit, name="groups.posts.edit"),
    path("groups/<int:pk>/posts/<int:post_id>/comment", gops.group_comment, name="groups.comment"),
    path("groups/<int:pk>/posts/<int:post_id>/delete", gops.group_post_delete, name="groups.posts.delete"),
    path("groups/<int:pk>/posts/<int:post_id>/like", gops.group_post_like, name="groups.posts.like"),
    path("groups/<int:pk>/comments/<int:comment_id>/delete", gops.group_comment_delete, name="groups.comments.delete"),
    path("groups/<int:pk>/comments/<int:comment_id>/like", gops.group_comment_like, name="groups.comments.like"),
    path("groups/<int:pk>/docs", gops.group_docs, name="groups.docs"),
    path("groups/<int:pk>/docs/<int:doc_id>", gops.group_doc_show, name="groups.docs.show"),
    path("groups/<int:pk>/docs/<int:doc_id>/delete", gops.group_doc_delete, name="groups.docs.delete"),
    path("groups/<int:pk>", browse.group_show, name="groups.show"),
    path("groups/<slug:slug>", browse.group_slug_redirect, name="groups.slug"),
    path("g/<slug:slug>", browse.group_slug_redirect, name="groups.vanity"),
    path("inbox", inbox.inbox_home, name="inbox"),
    path("inbox/compose", inbox.inbox_compose, name="inbox.compose"),
    path("inbox/read-all", inbox.inbox_read_all, name="inbox.read_all"),
    path("inbox/start/<int:pk>", inbox.inbox_start, name="inbox.start"),
    path("inbox/<int:conversation_id>/message", inbox.message_send, name="inbox.message"),
    path("inbox/<int:conversation_id>/leave", inbox.inbox_leave, name="inbox.leave"),
    path("inbox/<int:conversation_id>/unarchive", inbox.inbox_unarchive, name="inbox.unarchive"),
    path("inbox/<int:conversation_id>/mute", inbox.inbox_mute, name="inbox.mute"),
    path("inbox/<int:conversation_id>/unmute", inbox.inbox_unmute, name="inbox.unmute"),
    path("inbox/<int:conversation_id>/title", inbox.inbox_title, name="inbox.title"),
    path("inbox/<int:conversation_id>/since", rt.inbox_since, name="inbox.since"),
    path("inbox/<int:conversation_id>/typing", rt.inbox_typing, name="inbox.typing"),
    path("realtime/stream", rt.stream, name="realtime.stream"),
    path("messages/<int:message_id>/delete", inbox.message_delete, name="messages.delete"),
    # Legacy Messenger URLs → Inbox
    path("messenger", meta.redirect_permanent, {"to": "/inbox"}, name="messenger.legacy"),
    path("messenger/<path:rest>", meta.redirect_messenger_legacy),
    path("pokes", views.pokes, name="pokes"),
    path("notifications", views.notifications, name="notifications"),
    path("activity", meta.redirect_permanent, {"to": "/notifications"}, name="activity"),
    path("search", browse.search, name="search"),
    path("albums", albums.albums, name="albums"),
    path("albums/<int:album_id>", albums.album_show, name="albums.show"),
    path("albums/<int:album_id>/edit", albums.album_edit, name="albums.edit"),
    path("albums/<int:album_id>/photos", albums.photo_upload, name="albums.photos"),
    path("albums/<int:album_id>/photos/<int:photo_id>", albums.photo_show, name="albums.photos.show"),
    path("albums/<int:album_id>/photos/<int:photo_id>/modal", albums.photo_modal, name="albums.photos.modal"),
    path("albums/<int:album_id>/photos/<int:photo_id>/comment", albums.photo_comment, name="albums.photos.comment"),
    path("albums/<int:album_id>/photos/<int:photo_id>/like", albums.photo_like, name="albums.photos.like"),
    path("albums/<int:album_id>/photos/<int:photo_id>/tag", albums.photo_tag, name="albums.photos.tag"),
    path(
        "albums/<int:album_id>/photos/<int:photo_id>/tags/<int:tag_id>/approve",
        albums.photo_tag_approve, name="albums.photos.tag.approve",
    ),
    path(
        "albums/<int:album_id>/photos/<int:photo_id>/tags/<int:tag_id>/decline",
        albums.photo_tag_decline, name="albums.photos.tag.decline",
    ),
    path(
        "albums/<int:album_id>/photos/<int:photo_id>/tags/<int:tag_id>/delete",
        albums.photo_tag_delete, name="albums.photos.tag.delete",
    ),
    path(
        "albums/<int:album_id>/photos/<int:photo_id>/comments/<int:comment_id>/delete",
        albums.photo_comment_delete, name="albums.photos.comment.delete",
    ),
    path(
        "albums/<int:album_id>/photos/<int:photo_id>/comments/<int:comment_id>/like",
        albums.photo_comment_like, name="albums.photos.comment.like",
    ),
    path("albums/<int:album_id>/photos/<int:photo_id>/caption", albums.photo_caption, name="albums.photos.caption"),
    path("albums/<int:album_id>/photos/<int:photo_id>/cover", albums.photo_cover, name="albums.photos.cover"),
    path("albums/<int:album_id>/photos/<int:photo_id>/delete", albums.photo_delete, name="albums.photos.delete"),
    path("albums/<int:album_id>/delete", albums.album_delete, name="albums.delete"),
    path("profile/<int:pk>/albums", albums.profile_albums, name="profile.albums"),
    path("events", events.events_home, name="events"),
    path("events/<int:event_id>/edit", events.event_edit, name="events.edit"),
    path("events/<int:event_id>/cover/clear", events.event_cover_clear, name="events.cover.clear"),
    path("events/<int:event_id>/delete", events.event_delete, name="events.delete"),
    path("events/<int:event_id>", events.event_show, name="events.show"),
    path("events/<int:event_id>/rsvp", events.event_rsvp, name="events.rsvp"),
    path("events/<int:event_id>/invite", events.event_invite, name="events.invite"),
    path("events/<int:event_id>/posts", events.event_post, name="events.posts"),
    path("events/<int:event_id>/posts/<int:post_id>/delete", events.event_post_delete, name="events.posts.delete"),
    path("profile/edit", act.profile_edit, name="profile.edit"),
    path("profile/status", act.status_update, name="profile.status"),
    path("profile/education", act.education_save, name="profile.education"),
    path("profile/education/<int:pk>", act.education_save, name="profile.education.edit"),
    path("profile/education/<int:pk>/delete", act.education_delete, name="profile.education.delete"),
    path("profile/experience", act.experience_save, name="profile.experience"),
    path("profile/experience/<int:pk>", act.experience_save, name="profile.experience.edit"),
    path("profile/experience/<int:pk>/delete", act.experience_delete, name="profile.experience.delete"),
    path("profile/avatar", act.avatar_upload, name="profile.avatar"),
    path("profile/avatar/clear", act.avatar_clear, name="profile.avatar.clear"),
    path("profile/<int:pk>/block", act.block_toggle, name="profile.block"),
    path("profile/<int:pk>/poke", act.poke, name="profile.poke"),
    path("profile/<int:pk>/relationship/<int:req_id>/accept", act.relationship_accept, name="relationship.accept"),
    path("profile/<int:pk>/relationship/<int:req_id>/decline", act.relationship_decline, name="relationship.decline"),
    path("feed/hide/<int:pk>", act.feed_hide_actor, name="feed.hide.actor"),
    path("feed/unhide/<int:pk>", act.feed_unhide_actor, name="feed.unhide.actor"),
    path("feed/hide-story", act.feed_hide_story, name="feed.hide.story"),
    path("family/request", act.family_request, name="family.request"),
    path("family/<int:pk>/accept", act.family_accept, name="family.accept"),
    path("family/<int:pk>/decline", act.family_decline, name="family.decline"),
    path("family/<int:pk>/remove", act.family_remove, name="family.remove"),
    path("profile/<int:pk>/walltowall", views.wall_to_wall, name="profile.walltowall"),
    path("profile/<int:pk>/friendship", views.see_friendship, name="profile.friendship"),
    path("profile/<int:pk>/friends", friends.profile_friends, name="profile.friends"),
    path("profile/<int:pk>/mutual", friends.mutual_friends_view, name="profile.mutual"),
    path("profile/<int:pk>", views.profile, name="profile"),
    path("profile/<slug:slug>", browse.profile_slug_redirect, name="profile.slug"),
    path("u/<slug:slug>", browse.profile_slug_redirect, name="profile.vanity"),
    path("posts", act.post_create, name="posts.store"),
    path("posts/<int:post_id>", wall.post_show, name="posts.show"),
    path("posts/<int:post_id>/edit", wall.post_edit, name="posts.edit"),
    path("posts/<int:post_id>/like", act.post_like, name="posts.like"),
    path("posts/<int:post_id>/share", act.post_share, name="posts.share"),
    path("posts/<int:post_id>/tag", act.post_tag, name="posts.tag"),
    path("posts/<int:post_id>/tags/<int:tag_id>/delete", act.post_tag_delete, name="posts.tag.delete"),
    path("posts/<int:post_id>/comment", act.comment_create, name="comments.store"),
    path("posts/<int:post_id>/delete", act.post_delete, name="posts.delete"),
    path("comments/<int:comment_id>/like", act.comment_like, name="comments.like"),
    path("comments/<int:comment_id>/delete", act.comment_delete, name="comments.delete"),
    path("friends/<int:pk>/request", friends.friend_request, name="friends.request"),
    path("friends/<int:pk>/accept", friends.friend_accept, name="friends.accept"),
    path("friends/<int:pk>/reject", friends.friend_reject, name="friends.reject"),
    path("friends/<int:pk>/cancel", friends.friend_cancel, name="friends.cancel"),
    path("friends/<int:pk>/remove", friends.friend_remove, name="friends.remove"),
    path("friends/<int:pk>/block", friends.friend_block, name="friends.block"),
    path("friends/<int:pk>/block/remove", friends.friend_unblock, name="friends.unblock"),
    path("about", meta.about, name="about"),
    path("terms", meta.terms, name="terms"),
    path("privacy", meta.privacy, name="privacy"),
    path("contacts", meta.contacts, name="contacts"),
    path("security", meta.security, name="security"),
    path("sitemap.xml", meta.sitemap, name="sitemap"),
    path("robots.txt", meta.robots, name="robots"),
]
