from django.urls import path
from . import views
from . import views_actions as act
from . import views_browse as browse
from . import views_group_ops as gops
from . import views_meta as meta
from . import views_albums as albums
from . import views_friends as friends
from . import views_events as events
from . import views_inbox as inbox
from . import views_wall_ops as wall

urlpatterns = [
    path("up", meta.up, name="up"),
    path("", views.home, name="home"),
    path("feed", views.feed, name="feed"),
    path("people", friends.people, name="people"),
    path("friends", friends.friends_home, name="friends"),
    path("invite", friends.invite_mine, name="invite.mine"),
    path("i/<str:code>", friends.invite_show, name="invite.show"),
    path("groups", browse.groups, name="groups"),
    path("groups/<int:pk>/edit", gops.group_edit, name="groups.edit"),
    path("groups/<int:pk>/members", gops.group_members, name="groups.members"),
    path("groups/<int:pk>/join", gops.group_join, name="groups.join"),
    path("groups/<int:pk>/leave", gops.group_leave, name="groups.leave"),
    path("groups/<int:pk>/join/cancel", gops.join_cancel, name="groups.join.cancel"),
    path("groups/<int:pk>/invite", gops.group_invite, name="groups.invite"),
    path("groups/<int:pk>/events", gops.group_event_create, name="groups.events"),
    path("groups/<int:pk>/members/<int:user_id>/manage", gops.member_manage, name="groups.members.manage"),
    path("groups/<int:pk>/join/<int:request_id>/accept", gops.join_accept, name="groups.join.accept"),
    path("groups/<int:pk>/join/<int:request_id>/reject", gops.join_reject, name="groups.join.reject"),
    path("groups/<int:pk>/posts", gops.group_post, name="groups.posts"),
    path("groups/<int:pk>/posts/<int:post_id>/edit", gops.group_post_edit, name="groups.posts.edit"),
    path("groups/<int:pk>/posts/<int:post_id>/comment", gops.group_comment, name="groups.comment"),
    path("groups/<int:pk>/posts/<int:post_id>/delete", gops.group_post_delete, name="groups.posts.delete"),
    path("groups/<int:pk>/comments/<int:comment_id>/delete", gops.group_comment_delete, name="groups.comments.delete"),
    path("groups/<int:pk>", browse.group_show, name="groups.show"),
    path("groups/<slug:slug>", browse.group_slug_redirect, name="groups.slug"),
    path("g/<slug:slug>", browse.group_slug_redirect, name="groups.vanity"),
    path("inbox", inbox.inbox_home, name="inbox"),
    path("inbox/compose", inbox.inbox_compose, name="inbox.compose"),
    path("inbox/start/<int:pk>", inbox.inbox_start, name="inbox.start"),
    path("inbox/<int:conversation_id>/message", inbox.message_send, name="inbox.message"),
    path("inbox/<int:conversation_id>/leave", inbox.inbox_leave, name="inbox.leave"),
    path("messages/<int:message_id>/delete", inbox.message_delete, name="messages.delete"),
    # Legacy Messenger URLs → Inbox
    path("messenger", meta.redirect_permanent, {"to": "/inbox"}, name="messenger.legacy"),
    path("messenger/<path:rest>", meta.redirect_messenger_legacy),
    path("pokes", views.pokes, name="pokes"),
    path("activity", meta.redirect_permanent, {"to": "/pokes"}, name="activity"),
    path("notifications", meta.redirect_permanent, {"to": "/pokes"}, name="notifications"),
    path("search", browse.search, name="search"),
    path("albums", albums.albums, name="albums"),
    path("albums/<int:album_id>", albums.album_show, name="albums.show"),
    path("albums/<int:album_id>/edit", albums.album_edit, name="albums.edit"),
    path("albums/<int:album_id>/photos", albums.photo_upload, name="albums.photos"),
    path("albums/<int:album_id>/photos/<int:photo_id>", albums.photo_show, name="albums.photos.show"),
    path("albums/<int:album_id>/photos/<int:photo_id>/comment", albums.photo_comment, name="albums.photos.comment"),
    path(
        "albums/<int:album_id>/photos/<int:photo_id>/comments/<int:comment_id>/delete",
        albums.photo_comment_delete, name="albums.photos.comment.delete",
    ),
    path("albums/<int:album_id>/photos/<int:photo_id>/caption", albums.photo_caption, name="albums.photos.caption"),
    path("albums/<int:album_id>/photos/<int:photo_id>/cover", albums.photo_cover, name="albums.photos.cover"),
    path("albums/<int:album_id>/photos/<int:photo_id>/delete", albums.photo_delete, name="albums.photos.delete"),
    path("albums/<int:album_id>/delete", albums.album_delete, name="albums.delete"),
    path("profile/<int:pk>/albums", albums.profile_albums, name="profile.albums"),
    path("events", events.events_home, name="events"),
    path("events/<int:event_id>", events.event_show, name="events.show"),
    path("events/<int:event_id>/rsvp", events.event_rsvp, name="events.rsvp"),
    path("events/<int:event_id>/invite", events.event_invite, name="events.invite"),
    path("profile/edit", act.profile_edit, name="profile.edit"),
    path("profile/status", act.status_update, name="profile.status"),
    path("profile/education", act.education_save, name="profile.education"),
    path("profile/education/<int:pk>", act.education_save, name="profile.education.edit"),
    path("profile/education/<int:pk>/delete", act.education_delete, name="profile.education.delete"),
    path("profile/experience", act.experience_save, name="profile.experience"),
    path("profile/experience/<int:pk>", act.experience_save, name="profile.experience.edit"),
    path("profile/experience/<int:pk>/delete", act.experience_delete, name="profile.experience.delete"),
    path("profile/avatar", act.avatar_upload, name="profile.avatar"),
    path("profile/avatar/clear", act.avatar_clear, name="profile.avatar.clear"),
    path("profile/<int:pk>/block", act.block_toggle, name="profile.block"),
    path("profile/<int:pk>/poke", act.poke, name="profile.poke"),
    path("profile/<int:pk>/walltowall", views.wall_to_wall, name="profile.walltowall"),
    path("profile/<int:pk>/friends", friends.profile_friends, name="profile.friends"),
    path("profile/<int:pk>/mutual", friends.mutual_friends_view, name="profile.mutual"),
    path("profile/<int:pk>", views.profile, name="profile"),
    path("profile/<slug:slug>", browse.profile_slug_redirect, name="profile.slug"),
    path("u/<slug:slug>", browse.profile_slug_redirect, name="profile.vanity"),
    path("notes", act.note_create, name="notes.store"),
    path("posts", act.post_create, name="posts.store"),
    path("posts/<int:post_id>", wall.post_show, name="posts.show"),
    path("posts/<int:post_id>/edit", wall.post_edit, name="posts.edit"),
    path("posts/<int:post_id>/comment", act.comment_create, name="comments.store"),
    path("posts/<int:post_id>/delete", act.post_delete, name="posts.delete"),
    path("comments/<int:comment_id>/delete", act.comment_delete, name="comments.delete"),
    path("friends/<int:pk>/request", friends.friend_request, name="friends.request"),
    path("friends/<int:pk>/accept", friends.friend_accept, name="friends.accept"),
    path("friends/<int:pk>/reject", friends.friend_reject, name="friends.reject"),
    path("friends/<int:pk>/cancel", friends.friend_cancel, name="friends.cancel"),
    path("friends/<int:pk>/remove", friends.friend_remove, name="friends.remove"),
    path("friends/<int:pk>/block", friends.friend_block, name="friends.block"),
    path("friends/<int:pk>/block/remove", friends.friend_unblock, name="friends.unblock"),
    path("about", meta.about, name="about"),
    path("terms", meta.terms, name="terms"),
    path("privacy", meta.privacy, name="privacy"),
    path("contacts", meta.contacts, name="contacts"),
    path("security", meta.security, name="security"),
    path("sitemap.xml", meta.sitemap, name="sitemap"),
    path("robots.txt", meta.robots, name="robots"),
]
